### ISSUE TITLE
os.path.realpath() returns a different path from the one hdiutil knows

### ISSUE THREAD

**Issue by Jonathan-David7** [0xbf00/dmglib#9]
When trying to detach an image (if it is already attached), `dmglib` checks if the image is indeed already attached using `dmg_already_attached()`, which uses `os.path.realpath()` to check the image's path.

When the user on macOS uses a directory from `/var` it is in fact mapped to `/private/var` and so `os.path.realpath()` returns a different address from what `hdiutil` knows, leading to an `InvalidOperation` exception being raised and `dmglib` being unable to detach the image, even though it is indeed attached.

**Reproduction instructions**: Use a temporary directory using Python's `tempfile` on Mac.

**Solution**: Use `os.path.realpath()` when attaching as well :)

**Comment by 0xbf00** [comment]
Thank you for creating this issue! I'll look into this soon. If you'd like to expedite the process, feel free to submit a PR. Thanks!

**Comment by Jonathan-David7** [comment]
Fantastic, created #10 , would appreciate your support in merging it 😎

**Comment by 0xbf00** [comment]
Changes are live in [v0.9.6](https://pypi.org/project/dmglib/0.9.6/) on PyPI.

Thanks for your contribution!
